import React from "react";
import ChartView from "./ChartView.jsx";
import DataTable from "./DataTable.jsx";
import { jsPDF } from "jspdf";
import "jspdf-autotable";

const PROJECT_NAME = "Pune Property Insights AI";

const ResponseCard = ({ summary, charts, table }) => {

  const exportPDF = async () => {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 15;

    // ------------ HEADER ------------
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(PROJECT_NAME, pageWidth / 2, y, { align: "center" });
    y += 7;

    doc.setFont("normal");
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: "center" });
    y += 10;

    // ------------ SUMMARY ------------
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("📌 AI Market Summary", 10, y);
    y += 6;

    doc.setFont("normal");
    doc.setFontSize(10);
    const summaryLines = doc.splitTextToSize(summary || "⚠ No AI insights available.", pageWidth - 20);
    doc.text(summaryLines, 10, y);
    y += summaryLines.length * 5 + 8;

    // ------------ CHART EXPORT ------------
    if (charts && charts.length > 0) {
      for (const chart of charts) {

        const chartNode = document.getElementById(`chart-${chart.id}`);

        if (chartNode) {
          const canvas = chartNode.querySelector("canvas");

          if (canvas) {
            const imgData = canvas.toDataURL("image/png", 1.0);

            if (y > 230) {
              doc.addPage();
              y = 15;
            }

            doc.setFont("helvetica", "bold");
            doc.setFontSize(12);
            doc.text(`📈 ${chart.title}`, 10, y);
            y += 5;

            doc.addImage(imgData, "PNG", 10, y, pageWidth - 20, 60);
            y += 70;
          }
        }
      }
    }

    // ------------ TABLE SECTION ------------
    if (table && table.rows?.length > 0) {
      if (y > 220) {
        doc.addPage();
        y = 15;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("📊 Data Table", 10, y);
      y += 5;

      const columns = table.columns;
      const rows = table.rows.map((row) => columns.map((c) => row[c] ?? ""));

      doc.autoTable({
        startY: y,
        head: [columns],
        body: rows,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [25, 118, 210] },
        theme: "grid",
        margin: { left: 10, right: 10 },
      });

      y = doc.lastAutoTable.finalY + 8;
    }

    // ------------ FOOTER ------------
    doc.setFont("italic");
    doc.setFontSize(9);
    doc.text(
      "Generated by Pune Property Insights AI — Real Estate Data Assistant",
      pageWidth / 2,
      290,
      { align: "center" }
    );

    doc.save("RealEstate_Report.pdf");
  };

  return (
    <div className="card mb-3 border-0 shadow-sm">
      <div className="card-body">
        <h5 className="card-title">AI Insight</h5>
        <p className="card-text">{summary || "⚠ No AI summary available."}</p>

        {/* ------ CHARTS ------ */}
        {charts?.length > 0 && (
          <div className="mt-2">
            {charts.map((chart) => (
              <div key={chart.id} id={`chart-${chart.id}`}>
                <ChartView chart={chart} />
              </div>
            ))}
          </div>
        )}

        {/* ------ TABLE ------ */}
        <DataTable table={table} />

        {/* ------ DOWNLOAD OPTION ------ */}
        <div className="mt-3">
          <h6 className="fw-semibold mb-2">Export Full Report</h6>
          <button className="btn btn-success btn-sm" onClick={exportPDF}>
            📄 Download PDF Report
          </button>
        </div>
      </div>
    </div>
  );
};

export default ResponseCard;
